SchoolDues/BananaPlanerMVC/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Mvc;
using SchoolDuesLib.Models;
using SchoolDuesLib.Providers;

namespace BananaPlanerMVC.Controllers
{
    [Authorize]
    public class EventController : BaseController
    {
        public ActionResult Get(int id)
        {
            var model = new EventDataProvider(GetUserName()).GetEventAsAdmin(id, User.Identity.Name);
            return View(model);
        }

        public ActionResult Index()
        {
            var eventDataProvider = new EventDataProvider(GetUserName());
            return View(eventDataProvider.GetEventsCanAdmin(fromDate:DateTime.Today).ToList());
        }

        public ActionResult Past()
        {
            return View(new EventDataProvider(GetUserName()).GetEventsCanAdmin(fromDate:new DateTime(1970,1,1), toDate:DateTime.Today).ToList());
        }

        private void PrepareViewModelForAddUpdateScreen(Event model)
        {
/*
            List<School> userSchools = new SchoolDataProvider(GetUserName()).GetUserSchools(User.Identity.Name);
            ViewBag.Schools = userSchools;
*/
            if (model.School != null)
            {
                model.SchoolId = model.School.Id;
                model.SchoolRelated = true;
            }
            else
            {
                model.SchoolRelated = false;
            }
            if (model.StartTime != null)
            {
                model.Date = model.StartTime.Value;
            }
            if (model.FundsTotal != null)
            {
                model.FundSelection = 2;
            } 
            else if (model.FundsPerPerson != null)
            {
                model.FundSelection = 1;
            }
            else
            {
                model.FundSelection = 0;
            }
        }

        public ActionResult Create()
        {
            var date = DateTime.Today.AddDays(1);
            var model = new Event
            {
                Date = date,
                StartTime = new DateTime(date.Year, date.Month, date.Day, 11, 0, 0),
                EndTime = new DateTime(date.Year, date.Month, date.Day, 13, 0, 0),
            };

            PrepareViewModelForAddUpdateScreen(model);

//            model.SchoolRelated = ((IList<School>) ViewBag.Schools).Any();
            return View("AddUpdate", model);
        }

        [HttpPost]
        public ActionResult Create(Event model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedOn = DateTime.Now;
                model.IsDraft = true;

                UpdateModelFromViewModel(model);
                model = new EventDataProvider(GetUserName()).CreateEvent(model, User.Identity.Name);

                if (model.NeedVolunteers == true)
                {
                    return RedirectToAction("Volunteers", new { id = model.Id });
                }
                if (model.NeedSupplies == true)
                {
                    return RedirectToAction("Supplies", new { id = model.Id });
                }
                return RedirectToAction("Invite", new {id = model.Id});
            }

            PrepareViewModelForAddUpdateScreen(model);
            return View("AddUpdate", model);
        }

        public ActionResult Edit(int id)
        {
            var model = new EventDataProvider(GetUserName()).GetEventAsAdmin(id);
            PrepareViewModelForAddUpdateScreen(model);
            return View("AddUpdate", model);
        }

        [HttpPost]
        public ActionResult Edit(Event model)
        {
            if (ModelState.IsValid)
            {
                model.UpdatedOn = DateTime.Now;

                UpdateModelFromViewModel(model);
                model = new EventDataProvider(GetUserName()).UpdateEvent(model, User.Identity.Name);

                if (model.NeedVolunteers == true)
                {
                    return RedirectToAction("Volunteers", new { id = model.Id });
                }
                if (model.NeedSupplies == true)
                {
                    return RedirectToAction("Supplies", new { id = model.Id });
                }
                return RedirectToAction("Invite", new { id = model.Id });
            }

            PrepareViewModelForAddUpdateScreen(model);
            return View("AddUpdate", model);
        }

        private static void UpdateModelFromViewModel(Event model)
        {
            Debug.Assert(model.StartTime != null);
            Debug.Assert(model.EndTime != null);

            if (!model.SchoolRelated)
            {
                model.School = null;
                model.SchoolId = null;
            }

            model.StartTime = new DateTime(model.Date.Year, model.Date.Month, model.Date.Day,
                                           model.StartTime.Value.Hour, model.StartTime.Value.Minute, 0, model.StartTime.Value.Kind);

            model.EndTime = new DateTime(model.Date.Year, model.Date.Month, model.Date.Day,
                                         model.EndTime.Value.Hour, model.EndTime.Value.Minute, 0, model.StartTime.Value.Kind);


        }

        public ActionResult Volunteers(int id)
        {
            var model = new EventDataProvider(GetUserName()).GetEventAsAdmin(id, User.Identity.Name);
/*
            PrepareViewModelForAddUpdateScreen(model);
            model.VolunteerSpots.Add(new VolunteerSpot {Comments = "Test", NumberOfVolunteers = 2, StartTime = DateTime.Now, EndTime = DateTime.Now.AddHours(1)});
            model.VolunteerSpots.Add(new VolunteerSpot { Comments = "Test2", NumberOfVolunteers = 20, StartTime = DateTime.Now, EndTime = DateTime.Now.AddHours(1) });
*/

            if (model.NeedVolunteers == true && model.VolunteerSpots.Count == 0)
            {
                model.VolunteerSpots.Add(CreateEmptyVolunteerSpot(model));
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Volunteers(Event model, string button)
        {
            if (button != "Add Volunteer Spot")
            {
                model = new EventDataProvider(GetUserName()).UpdateEventVolunteers(model, User.Identity.Name);
                return RedirectToAction(GetNextEventScreen("Volunteers", model), new { id = model.Id });
            }

            // read the event from DB so we can use start/end time to create new volunteer spot
            var curModel = new EventDataProvider(GetUserName()).GetEventAsAdmin(model.Id, User.Identity.Name);
            model.VolunteerSpots.Add(CreateEmptyVolunteerSpot(curModel));
            
            model = new EventDataProvider(GetUserName()).UpdateEventVolunteers(model, User.Identity.Name);
            return RedirectToAction("Volunteers", new { id = model.Id });
        }

        private static VolunteerSpot CreateEmptyVolunteerSpot(Event model)
        {
            var volSpot = new VolunteerSpot
                {
                    NumberOfVolunteers = 1
                };
            if (model.StartTime != null)
            {
                volSpot.StartTime = model.StartTime.Value;
            }
            if (model.EndTime != null)
            {
                volSpot.EndTime = model.EndTime.Value;
            }
            return volSpot;
        }

        public ActionResult Supplies(int id)
        {
            var model = new EventDataProvider(GetUserName()).GetEventAsAdmin(id, User.Identity.Name);
            if (model.Supplies.Any())
            {
                ViewBag.SuppliesString = string.Join("\r\n", model.Supplies.Select(s => s.Description));
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Supplies(Event model, string supplies, string nextPage)
        {
            new EventDataProvider(GetUserName()).UpdateSupplies(model, Split(supplies), User.Identity.Name);
            return RedirectToAction(GetNextEventScreen("Supplies", model), new { id = model.Id});
        }

        private string GetNextEventScreen(string currentScreenName, Event ev)
        {
            var hiddenField = HttpContext.Request["nextPage"];
            if (!string.IsNullOrWhiteSpace(hiddenField))
            {
                return hiddenField;
            }
            switch (currentScreenName)
            {
                case "Supplies":
                    return "Invite";
                case "Volunteers":
                    return ev.NeedSupplies == true ? "Supplies" : "Invite";
                case "Invite":
                    return "Get";

            }
            return null;
        }


        public ActionResult Invite(int id)
        {
            var model = new EventDataProvider(GetUserName()).GetEventAsAdmin(id, User.Identity.Name);
            if (model.Invitations.Any())
            {
                ViewBag.Emails = string.Join("\r\n", model.Invitations.Select(s => s.Parent.Email));
            }
            var otherAdmins = model.Admins.Where(a => a.UserName != User.Identity.Name).ToList();
            if (otherAdmins.Any())
            {
                ViewBag.Admins = string.Join("\r\n", otherAdmins.Select(a => a.Email));
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult Invite(Event model, string emails, string admins)
        {
            new EventDataProvider(GetUserName()).UpdateInvites(model, Split(emails),  User.Identity.Name, GetSiteBaseUrl());
            new EventDataProvider(GetUserName()).UpdateAdmins(model, Split(admins), User.Identity.Name);
            return RedirectToAction(GetNextEventScreen("Invite", model), new { id = model.Id });
        }

        private string[] Split(string fullStr)
        {
            return fullStr.Split('\r', '\n').Where(s => !string.IsNullOrWhiteSpace(s)).Select(s=>s.Trim()).ToArray();
        }

        public ActionResult Publish(int id)
        {

SchoolDues/BananaPlanerMVC/Views/Event/AddUpdate.cshtml
@using SchoolDuesLib.Models
@using SchoolDuesLib.Providers
@model SchoolDuesLib.Models.Event
@{
    ViewBag.Title = "Edit Event";
    Layout = "~/Views/Shared/_EventLayout.cshtml";
    var userProfile = new UserDataAccess(User.Identity.Name).GetUserProfileByUserName(User.Identity.Name);
//    var noSchools = !((IList<School>)ViewBag.Schools).Any();
}
@using (Html.BeginForm(ViewContext.RouteData.GetRequiredString("action"), "Event", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <h4>Event Details</h4>
@*
    if (noSchools)
    {
         <div class="alert">There are no schools configured.
             You can either add school you want manage to @Html.ActionLink("your profile", "My", "Account") in addition you can create
             events for the schools where you children are enrolled.
        </div>
    }
*@

    <div class='white-card'>
@*
        <div class="row">
            <div class="span3">
                <label class="radio">
                    @if (noSchools)
                    {
                    @Html.RadioButtonFor(m => m.SchoolRelated, "true", new { id = "schoolRelated", disabled = "disabled" })
                    }
                    else
                    {
                    @Html.RadioButtonFor(m => m.SchoolRelated, "true", new { id = "schoolRelated" })
                    }
                    @Html.Label("schoolRelated", "School Related")
                </label>
                <label class="radio">
                    @Html.RadioButtonFor(m => m.SchoolRelated, "false", new { id = "notSchoolRelated" })
                    @Html.Label("notSchoolRelated", "Not School Related")
                </label>
            </div>
            <div class="span3"></div>
            <div class="span2"></div>
        </div>
        <div class="row" id="schoolDiv">
            @if (!noSchools)
            {
            <div class="row">&nbsp;</div>
            <div class="span4">
                @Html.LabelFor(m => m.SchoolId)
                @Html.DropDownListFor(m => m.SchoolId, new SelectList(ViewBag.Schools, "Id", "Name"), new { @class = "span4" })
            </div>
            <div class="span5">
                @Html.LabelFor(m => m.Teachers)
                @Html.TextBoxFor(m => m.Teachers, new { @class = "span5", placeholder = "Mrs. Smith, Mr. Jones" })
            </div>
            }
        </div>
        <div class="row">&nbsp;</div>
*@
        <div class="row">
            <div class="span3">
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { placeholder = "Museum class trip", @class = "span5" })
                <p>@Html.ValidationMessageFor(m => m.Name)</p>
            </div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="span3">
                @Html.LabelFor(m => m.Description)
                @Html.TextAreaFor(m => m.Description, new { rows = "5", @class = "span8", cols = "20" })
            </div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="span3">
                @Html.LabelFor(m => m.Date)
                <div class="input-append date" id="eventDate" data-date="12-02-2012" data-date-format="mm/dd/yyyy">
                    @Html.TextBoxFor(m => m.Date, "{0:MM/dd/yyyy}", new { @class = "input-small", size = "16", type = "text" })
                    <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
            </div>
            <div class="span3">
                @Html.LabelFor(m => m.StartTime)
                <div class="input-append bootstrap-timepicker" >
                    @*                    @Html.TextBoxFor(m => m.StartTime, "{0:hh:mm tt}")*@
                    @Html.TextBoxFor(m => m.StartTime, "{0:hh:mm tt}", new { @class = "input-small", size = "16", type = "text", id = "timeStart" })
                    <span class="add-on"><i class="icon-time"></i></span>
                </div>
                <p>@Html.ValidationMessageFor(m => m.StartTime)</p>

            </div>
            <div class="span3">
                @Html.LabelFor(m => m.EndTime)
                <div class="input-append bootstrap-timepicker" >
                    @Html.TextBoxFor(m => m.EndTime, "{0:hh:mm tt}", new { @class = "input-small", size = "16", type = "text", id = "timeEnd" })
                    <span class="add-on"><i class="icon-time"></i></span>
                </div>
                <p>@Html.ValidationMessageFor(m => m.EndTime)</p>
            </div>
        </div>
        <div class="row">&nbsp;</div>
        <div class="row">
            <div class="span3">
                @Html.LabelFor(m => m.Location)
                @Html.TextAreaFor(m => m.Location, new { rows = "4", @class = "span5", cols = "20" })
            </div>
        </div>
    </div>
    <h4>Funds</h4>
        if (!userProfile.PaymentAccounts.Any())
        {
    <div class="alert">You need to configure Dwolla on 
        @Html.ActionLink("your account", "My", "Account")
        before you can collect funds through BananaPlanr. Dwolla is a low cost online payments system that 
        transfers money from bank accounts rather than credit cards. It saves money for your school by not paying high credit card fees.
        More information available at <a href="http://dwolla.com">Dwolla.com</a>.
            </div>
        }
    <div class='white-card'>
        <div class="row">
            <div class="span4">
                <label>Will you be collecting funds?</label>
                <div>
                    <label class="radio">
                        @if (!userProfile.PaymentAccounts.Any())
                        {
                            @Html.RadioButtonFor(m => m.FundSelection, "1", new { id = "perPerson", disabled = "disabled" })
                            @Html.Label("perPerson", "Yes, I need each participant to contribute", new { @class = "disabled" })
                        }
                        else
                        {
                            @Html.RadioButtonFor(m => m.FundSelection, "1", new { id = "perPerson" })
                            @Html.Label("perPerson", "Yes, I need each participant to contribute")
                        }
                    </label>
                    @*
                    <label class="radio">
                        @Html.RadioButtonFor(m=>m.FundSelection, "2", new {id="total"})
                        @Html.Label("total", "Yes, but I need to raise a goal amount")
                    </label>
    *@
                    <label class="radio">
                        @Html.RadioButtonFor(m => m.FundSelection, "0", new { id = "null" })
                        @Html.Label("null", "No")
                    </label>
                </div>
            </div>
            <div class="span3" id="perPersonDiv">
                @Html.LabelFor(m => m.FundsPerPerson)
                <div class="input-prepend input-append">
                    <span class="add-on">$</span>
                    @Html.TextBoxFor(m => m.FundsPerPerson, new { @class = "span2", placeholder = "0.00" })
                </div>
            </div>
@*
            <div class="span2" id="totalDiv">
                @Html.LabelFor(m=>m.FundsTotal)
                <div class="input-prepend input-append">
                    <span class="add-on">$</span>
                    @Html.TextBoxFor(m=>m.FundsTotal, new {@class="span2",placeholder="0.00"})
                </div>
            </div>
*@
        </div>
    </div>
    <h4>Additional Information</h4>
    <div class='white-card'>
        <div class="row">
            <div class="span5">
                <label>Will this event be requiring volunteers or sign-ups?</label>
                <label class="radio">
                    @Html.RadioButtonFor(m => m.NeedVolunteers, "true", new { id = "yesVoluntters" })
                    @Html.Label("yesVoluntters", "Yes, I will add volunteers next")
                </label>
                <label class="radio">
                    @Html.RadioButtonFor(m => m.NeedVolunteers, "false", new { id = "noVoluntters" })
                    @Html.Label("noVoluntters", "No")
                </label>
                                <p>@Html.ValidationMessageFor(m => m.NeedVolunteers)</p>

            </div>
            <div class="span4">
                <label>Will you be collecting supplies for this event?</label>
                <div>
                <label class="radio">
                    @Html.RadioButtonFor(m => m.NeedSupplies, "true", new { id = "yesSupplies" })
                    @Html.Label("yesSupplies", "Yes, I will provide a list of supplies")
                </label>
                    <label class="radio">
                        @Html.RadioButtonFor(m => m.NeedSupplies, "false", new { id = "noSupplies" })
                        @Html.Label("noSupplies", "No")
                    </label>
                    <p>@Html.ValidationMessageFor(m => m.NeedSupplies)</p>

                </div>
            </div>
        </div>
    </div>
    @Html.ValidationSummary()
    <input type="submit" value="Next" class="btn" />
}
@section scriptbottom
{
    @Scripts.Render("~/bundles/bootstraper-datetime")
    @Styles.Render("~/Content/bootstraper-datetime")
    <script type="text/javascript">

        function domAttrModified(obj) {
            $(obj).bind('DOMAttrModified', function () {
                if ($(obj).attr('class').indexOf('input-validation-error') != -1)
                    $(obj).parent().addClass('input-validation-error');
                else
                    $(obj).parent().removeClass('input-validation-error');
            });
        }
        
        $(document).ready(function () {
            
            $('[name=NeedVolunteers]').each(function (index) { domAttrModified(this); });
            $('[name=NeedSupplies]').each(function (index) { domAttrModified(this); });

            $("#eventDate").datepicker();
            $("#timeStart").timepicker({ defaultTime: false });
            $("#timeEnd").timepicker({ defaultTime: false });

            @if (Model.FundsTotal != null)
            {
                @:$('#perPersonDiv').hide();
            }
            else if (Model.FundsPerPerson != null)
            {
                @:$('#totalDiv').hide();
            }
            else
            {
                @:$('#perPersonDiv').hide();
                @:$('#totalDiv').hide();
            }
            

            $("input[name$='FundSelection']").click(function () {
                switch ($(this).val()) {
                case "1":
                    $('#perPersonDiv').show();
                    break;
                case "2":
                    $('#perPersonDiv').hide();
                    break;
                case "0":
                    $('#perPersonDiv').hide();
                    break;
                }
            });
            $("input[name$='SchoolRelated']").click(function () {
                switch ($(this).val()) {
                case "true":
                    $('#schoolDiv').show();
                    break;
                case "false":
                    $('#schoolDiv').hide();
                    break;
                }
            });
            @if (!Model.SchoolRelated)
            {
                @:$('#schoolDiv').hide();
            }
        });
    </script>
@*
        @Scripts.Render("~/bundles/jqueryval") // remove client side validation as it doesn't work with time field
*@
}

SchoolDues/BananaPlanerMVC/Views/Event/Get.cshtml
@using BananaPlanerMVC.Models
@using BananaPlanerMVC.Utils
@using SchoolDuesLib.Models
@model Event

@{
    ViewBag.Title = "Event Details";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    var selfInvite = Model.Invitations.FirstOrDefault(i => i.Parent.UserName == User.Identity.Name);
}
@if(Model.IsDraft)
{
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> This event is still in Draft mode and only visible to you. Please remember to publish it.
    </div>
}
<div>
    <div class="row">
        <div class="pull-right">
            <div class="btn-group">
                @Html.ActionLink("Edit", "Edit", "Event", new {Id = Model.Id}, new {@class="btn btn-primary"})
                @if(!Model.IsDraft)
                {
@*                    <a class="btn btn-primary hidden-tablet" href="#">Print</a>*@
                    if(selfInvite != null)
                     {
                         @Html.ActionLink("View as Parent", "Get", "Invite", new {selfInvite.Id}, new {@class="btn btn-primary"})
                     }
@*
                    <a class="btn btn-primary" href="#">Add Event</a>
                    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Add Event</a></li>
                        <li><a href="#">Add Event using same recipients</a></li>
                    </ul>
*@
                }
            </div>
            @if (Model.IsDraft)
            {
                <div class="btn-group">
                    <a class="btn btn-primary" href="@Url.Action("Publish", "Event", new { Id = Model.Id })">Publish</a>
                </div>
            }
        </div>
    </div>
    <div class="row">
        &nbsp;
    </div>
    <div class="row">
        <div class='span3'>
            <div class="white-card">
                @Model.Name<br/>
                Location: @Model.Location
            </div>
        </div>
        <div class='span3'>
            <div class="white-card">
                Date: @Model.StartTime.Value.ToShortDateString()<br/>
                Time: @(Model.StartTime.Value.ToShortTimeString() + " - " + Model.EndTime.Value.ToShortTimeString())<br/>
            </div>
        </div>
        @if(Model.SchoolRelated)
        {
            <div class='span3'>
                <div class="white-card">
                    Teacher: @Model.Teachers
                    <br/>@*Classroom:*@
                </div>
            </div>
        }
        else
        {
            <div class='span3'>
                <div class="white-card">
                    Organizer: @Model.CreatedBy.Format(false)
                    <br/>@*Classroom:*@
                </div>
            </div>
        }
    </div>
    <div class="row">
        <div class="span9">
            <div class="white-card">
                @foreach (var line in Model.Description.Split('\r'))
                {
                    @line <br/>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class='span6'>
            <div class="white-card">
                <h4 class="span2 no-margin-span">Participants </h4>
                @Html.ActionLink("Edit", "Invite", new {id = Model.Id}, new {@class="btn pull-right"})
                
                <table class="table">
                    <thead>
                        <tr>
                            <th colspan="1">Name</th>
                            @if(!Model.IsDraft)
                            {
                                <th colspan="1">Accepted</th>
                            }
                        </tr>
                    </thead>
                    @foreach (var invite in Model.Invitations.Where(i => i.Parent != null))
                    {
                        <tr><td>@invite.Parent.Email</td>
                            @if (!Model.IsDraft)
                            {
                                <td>
                                    @if (invite.Status == InvitationStatus.Accepted)
                                    {
                                        <i class="icon-check"/>
                                    }
                                    else
                                    {
                                        <i class="icon-check-empty"/>
                                    }
                                </td>                            }
                        </tr>
                    }
                </table>
                @if (!Model.IsDraft)
                {
                    <div class="btn-group">
                        <a class="btn btn-primary hidden-tablet" href="#">Print</a>
                        <a class="btn btn-primary" href="#"  onclick="send('@SendMailAction.AllParticipants', @Model.Id, 'To All Participants');">Email All</a>
                        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#" onclick="send('@SendMailAction.AllParticipants', @Model.Id, 'To All Participants');">Email All</a></li>
                            <li><a href="#" onclick="send('@SendMailAction.AcceptedParticipants', @Model.Id, 'To Participants who accepted the invite');">Email Accepted</a></li>
                            <li><a href="#" onclick="send('@SendMailAction.NotAcceptedParticipants', @Model.Id, 'To Participants who did not accept the invite');">Email Not Accepted</a></li>
                        </ul>
                    </div>
                }
            </div>
        </div>
        <div class='span3'>
            <div>
                <h4>Summary</h4>
                @if(Model.StartTime.Value > DateTime.Today)
                {
                <dl class="dl-horizontal">
                    <dt>Days Till Event</dt>
                    <dd>@((Model.StartTime.Value - DateTime.Today).Days)</dd>
                </dl>
                }
                @if (Model.FundsPerPerson != null || Model.FundsTotal != null)
                {
                    <dl class="dl-horizontal">
                        <dt>Amount Collected:</dt>
                        <dd>@string.Format("{0:c}",Model.Invitations.Count(i=>i.Order != null && i.Order.Status == OrderStatus.Complete) * Model.FundsPerPerson)</dd>
                    </dl>
                    <dl class="dl-horizontal">
                        <dt>Volunteers:</dt>
                        <dd>
                            @string.Format("{0} out of {1}", 
                                           Model.VolunteerSpots.SelectMany(v => v.Accepted).Count(), 
                                           Model.VolunteerSpots.Sum(v=>v.NumberOfVolunteers))
                        </dd>
                    </dl>
                }
                @if (Model.NeedSupplies == true)
                {
                    <dl class="dl-horizontal">
                        <dt>Supplies:</dt>
                        <dd>
                            <a href="#" id="supplies">
                                @string.Format("{0} out of {1}", Model.Supplies.Count(s => s.Accepted != null), Model.Supplies.Count)
                            </a>
                        </dd>
                    </dl>
                }
            </div>
        </div>
    </div>
    @if (Model.NeedVolunteers == true)
    {
        <div class="row">
            <div class='span6'>
                <div class="white-card">
                    <h4>Volunteers</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Time</th>
                                <th>Volunteers</th>
                            </tr>
                        </thead>
                        @foreach (var spot in Model.VolunteerSpots.OrderBy(s => s.StartTime).ThenBy(s => s.EndTime))
                        {
                            <tr>
                                <td>@string.Format("{0} - {1}", spot.StartTime.ToShortTimeString(), spot.EndTime.ToShortTimeString())</td>
                                <td>
                                    @foreach (var vol in spot.Accepted)
                                    {
                                        @vol.Format(false)<br/>
                                    }
                                </td></tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    }
</div>
@section scriptbottom
{
    <script type="text/javascript">
        $(document).ready(function() {
            $('#supplies').qtip({
                content:
                    {
                        text: '@(string.Format("Promised:{0}",
                                               string.Join(",", Model.Supplies.Where(s => s.Accepted != null).Select(s => s.Description)))) <p/>  @(
    string.Format("Still Needed:{0}",
                  string.Join(",", Model.Supplies.Where(s => s.Accepted == null).Select(s => s.Description))))'
                    },
                style: {
                    classes: 'myCustomClass' // max-width: 350px;
                },
                show: { event: 'click' }
            });
        });
    </script>
    @{ Html.RenderPartial("_SendEmail"); }
}