SchoolDues/BananaPlanerMVC/Controllers/DebugController.cs
using System;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BananaPlanerMVC.Utils;
using Microsoft.Web.WebPages.OAuth;
using SchoolDuesLib;
using SchoolDuesLib.Email;
using SchoolDuesLib.Utils;
using WebMatrix.WebData;

namespace BananaPlanerMVC.Controllers
{
    [Authorize(Roles = Constants.SystemAdminRoleName)]
    public class DebugController : BaseController
    {
        public ActionResult Index()
        {
            ViewBag.ConnectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"];
            return View();
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Error()
        {
            throw new Exception("Testing error");
        }

        public ActionResult LoginAs(int id)
        {
            WebSecurity.Logout();

            var user = new SiteContext().UserProfiles.First(u => u.Id == id);
            var account = OAuthWebSecurity.GetAccountsFromUserName(user.UserName).First();

            OAuthWebSecurity.Login(account.Provider, account.ProviderUserId, createPersistentCookie: false);
            return RedirectToAction("Index", "Dashboard");
        }
    }
}

SchoolDues/BananaPlanerMVC/Views/Debug/Index.cshtml
@using System.Configuration
<section class='section-wrapper stripped'>
    <div class='container'>
        <div class="row">
            Production Flag = @Convert.ToBoolean(ConfigurationManager.AppSettings["isProduction"])
            <p/>
            @if (Request.IsAuthenticated)
            {
                @:Authenticated as @User.Identity.Name
            }
            else
            {
                @: not authenticated
            }
            <br/>
            @ViewBag.ConnectionString
            <br/>
            <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
                <input type="hidden" name="cmd" value="_xclick">
                <input type="hidden" name="business" value="kilativ@gmail.com">
                <input type="hidden" name="lc" value="US">
                <input type="hidden" name="item_name" value="Zoo Trip">
                <input type="hidden" name="item_number" value="123">
                <input type="hidden" name="amount" value="5.00">
                <input type="hidden" name="currency_code" value="USD">
                <input type="hidden" name="button_subtype" value="services">
                <input type="hidden" name="tax_rate" value="0.000">
                <input type="hidden" name="shipping" value="0.00">
                <input name="notify_url" value="http://requestb.in/12ooqvd1" type="hidden">
                <input type="hidden" name="bn" value="PP-BuyNowBF:btn_paynowCC_LG.gif:NonHosted">
                <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_paynowCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
            <p>&nbsp;</p>

        </div>                
    </div>
</section>

SchoolDues/BananaPlanerMVC/Views/Debug/Login.cshtml
@using SchoolDuesLib
@using SchoolDuesLib.Providers
@model dynamic

@{
    ViewBag.Title = "title";
    var users = new SiteContext().UserProfiles.ToList();
}

<h2>title</h2>


@foreach(var user in users)
{
     @Html.ActionLink(string.Format("{0} {1} - {2} {3}", user.FirstName, user.LastName, user.Email, user.Id), "LoginAs", "Debug", new {id = user.Id}, null)<br/>
}

SchoolDues/BananaPlanerMVC/Views/Debug/Test.cshtml
@model dynamic

@{
    ViewBag.Title = "Test";
}


<section class='section-wrapper'>
    <div class='container'>
        <div class='row'>
            <div class="span9">
                <a class="btn" id="demo">Launch demo modal</a>
            </div>
        </div>
    </div>
</section>

@section ScriptBottom
{
    @{ Html.RenderPartial("_SendEmail"); }
    <script>
        $("#demo").click(function() {
            send('h there', 1, 'To Students');
        });

    </script>
}