SchoolDues/BananaPlanerMVC/Controllers/InviteController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BananaPlanerMVC.Models;
using BananaPlanerMVC.Utils;
using Dwolla.Gateway;
using NLog;
using SchoolDuesLib.Models;
using SchoolDuesLib.Providers;
using SchoolDuesLib.Utils;

namespace BananaPlanerMVC.Controllers
{
    [Authorize(Roles = Constants.ParentRoleName)]
    public class InviteController : BaseController
    {
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();
        //
        // GET: /Invite/
        [AllowAnonymous]
        public ActionResult EmailLinkClicked(string id)
        {
            var byInviteId = new InviteDataProvider(GetUserName()).GetByInviteId(id);
            if (byInviteId == null)
            {
                return View("AppError", new AppErrorModel
                    {
                        Title = "Event not found",
                        Text = "This event was not found. It's possible the event ogranizer decided to delete this event.",
                        Header = "Event not found"
                    });
            }
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Get", new { byInviteId.Id });
            }
            UrlHelper u = new UrlHelper(ControllerContext.RequestContext);
            ViewBag.ReturnUrl = u.Action("Get", "Invite", new { byInviteId.Id });
            ViewBag.Id = id;
            return View("Login");
        }

        public ActionResult Accept(int id, int childId)
        {
            var inviteDataProvider = new InviteDataProvider(GetUserName());

            var model = inviteDataProvider.GetInvite(id, User.Identity.Name);

            if (model.Event.FundsPerPerson == null && model.Event.FundsTotal == null)
            {
                var inviteModel = inviteDataProvider.AcceptInvite(id, childId, User.Identity.Name);
                return RedirectToAction("Get", new { inviteModel.Id });
            }
            if (model.Event.FundsPerPerson != null)
            {
                string callbackUrl = "/Invite/Get/" + model.Id;

                var checkoutRedirectUrl = CreateDwollaUrl(childId, model, inviteDataProvider, callbackUrl);
                return Redirect(checkoutRedirectUrl);
            }
            return null;
        }

        [AllowAnonymous]
        public ActionResult AcceptGuest(int id, string uid)
        {
            var inviteDataProvider = new InviteDataProvider(GetUserName());
            var model = inviteDataProvider.GetByInviteId(uid);

            var child = new ChildDataAccess(GetUserName()).GetDefaultChild(model.Parent.Id);

            if (model.Event.FundsPerPerson == null && model.Event.FundsTotal == null)
            {
                var inviteModel = inviteDataProvider.AcceptInvite(id, child.Id, model.Parent.UserName ); // it's a hack to pass parent username but how else can we make a guest accept?
                return RedirectToAction("GetGuest", new { id = uid });
            }
            if (model.Event.FundsPerPerson != null)
            {
                var callbackUrl = "/Invite/GetGuest/" + uid;
                var checkoutRedirectUrl = CreateDwollaUrl(child.Id, model, inviteDataProvider, callbackUrl);
                return Redirect(checkoutRedirectUrl);
            }
            return null;
        }

        private string CreateDwollaUrl(int childId, Invitation model, InviteDataProvider inviteDataProvider,
                                           string callbackUrl)
        {
            var provider = model.Event.AcceptablePayments.FirstOrDefault(p => p.Provider == PaymentProvider.Dwolla);

            if (provider == null)
            {
                throw new Exception("No Dwolla Account");
            }

            var order = inviteDataProvider.CreateOrGet(model, childId, PaymentProvider.Dwolla);
            if (order.Status == OrderStatus.Complete)
            {
                throw new Exception("Already paid");
            }
            var key = provider.Key;
            var secret = provider.Secret;

            var isTestMode = !Convert.ToBoolean(ConfigurationManager.AppSettings["isProduction"]);

            var dwollaRequestService = new DwollaServerCheckoutApi(key, secret, isTestMode);
            var dwollaPurchaseOrder = new DwollaPurchaseOrder
                {
                    DestinationId = provider.AccountId
                };

            dwollaPurchaseOrder.OrderItems.Add(
                new DwollaOrderItem(model.Event.Name, model.Event.FundsPerPerson.Value, 1)
                    {
                        Description = model.Event.Description,
                    });

            var callback = new Uri(GetSiteBaseUrl() + "/Dwolla");
            logger.Debug("Callback {0}", callback);
            logger.Debug("isTestMode {0}", isTestMode);
            var dwollaCheckoutResponse = dwollaRequestService.SendCheckoutRequest(new DwollaCheckoutRequest
                {
                    AllowFundingSources = true,
                    Callback = callback, // to append userid to the end
                    Redirect = new Uri(GetSiteBaseUrl() + callbackUrl),
                    Key = key,
                    Secret = secret,
                    OrderId = order.Id.ToString(),
                    Test = isTestMode,
                    PurchaseOrder = dwollaPurchaseOrder
                });

            if (dwollaCheckoutResponse.Result == DwollaCheckoutResponseResult.Failure)
            {
                logger.Error("Failed to create dwolla request. Message = {0}", dwollaCheckoutResponse.Message);
            }

            var checkoutRedirectUrl = dwollaRequestService.GetCheckoutRedirectUrl(dwollaCheckoutResponse);
            logger.Debug("dwolla url = {0}", checkoutRedirectUrl);
            return checkoutRedirectUrl;
        }

        [AllowAnonymous]
        public ActionResult GetGuest(string id)
        {
            var dataProvider = new InviteDataProvider(GetUserName());
            var model = dataProvider.GetByInviteId(id);
            return View(model);
        }

        public ActionResult Get(int id)
        {
            var model = new InviteDataProvider(GetUserName()).GetInvite(id, User.Identity.Name);
            return View(model);
        }


        public ActionResult AcceptSupply(int id)
        {
            var invite = new InviteDataProvider(GetUserName()).AcceptSupply(id, User.Identity.Name);
            return RedirectToAction("Get", new {invite.Id});
        }

        [AllowAnonymous]
        public ActionResult AcceptSupplyGuest(int id, string uid)
        {
            var dataProvider = new InviteDataProvider(GetUserName());
            var model = dataProvider.GetByInviteId(uid);
            new InviteDataProvider(GetUserName()).AcceptSupply(id, model.Parent.UserName);
            return RedirectToAction("GetGuest", new { id = uid });
        }

        public ActionResult AcceptVolunteer(int id)
        {
            var invite = new InviteDataProvider(GetUserName()).AcceptVolunteer(id, User.Identity.Name);
            return RedirectToAction("Get", new { invite.Id });
        }

        [AllowAnonymous]
        public ActionResult AcceptVolunteerGuest(int id, string uid)
        {
            var dataProvider = new InviteDataProvider(GetUserName());
            var model = dataProvider.GetByInviteId(uid);
            var invite = new InviteDataProvider(GetUserName()).AcceptVolunteer(id, model.Parent.UserName);
            return RedirectToAction("GetGuest", new { id = uid });
        }

        public ActionResult Child(int id)//child id
        {
            var model = new InviteDataProvider(GetUserName()).GetInvitesByChildId(id, User.Identity.Name);
            ViewBag.Student  =  new ChildDataAccess(GetUserName()).GetStudentsById(id, User.Identity.Name);
            return View(model);
        }

    }
}

SchoolDues/BananaPlanerMVC/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BananaPlanerMVC.Models;
using BananaPlanerMVC.Utils;
using NLog;
using SchoolDuesLib.Models;
using SchoolDuesLib.Providers;
using SchoolDuesLib.Utils;

namespace BananaPlanerMVC.Controllers
{
    [Authorize(Roles = Constants.ParentRoleName)]
    public class StudentController : BaseController
    {
        private readonly IList<SelectListItem> gradesSelectListItems;
        private static readonly Logger log = LogManager.GetCurrentClassLogger();

        public StudentController()
        {
            gradesSelectListItems = new List<SelectListItem>
                {
                    new SelectListItem {Text = "K", Value = "K"}
                };
            for (int i = 1; i <=12; i++)
            {
                gradesSelectListItems.Add(new SelectListItem {Value = i.ToString(), Text = i.ToString()});
            }
        }

        public ActionResult Update(int? id)
        {
            ViewBag.Grades = gradesSelectListItems;
            if (id != null)
            {
                var student = new ChildDataAccess(GetUserName()).GetStudentsById(id.Value, User.Identity.Name);   
                return View(student);
            }
            return View();
        }
/*
        public ActionResult Edit(int Id)
        {
            ViewBag.Grades = gradesSelectListItems;
            var student = new ChildDataAccess(GetUserName()).GetStudentsById(Id, User.Identity.Name);   
            return View("Add", student);
        }
*/
        public ActionResult Add()
        {
            ViewBag.Grades = gradesSelectListItems;
            return RedirectToAction("Update");
        }
        /*

                public ActionResult Add()
                {
                    ViewBag.Grades = gradesSelectListItems;
                    return View();
                }
        */

        [HttpPost]
        public ActionResult Update(Student model)
        {
            if (ModelState.IsValid)
            {
                // todo validate that user has access to this student
                new ChildDataAccess(GetUserName()).CreateUpdateChild(model, User.Identity.Name);
                return RedirectToAction("My", "Account");
            }

            ViewBag.Grades = gradesSelectListItems;
            return View(model);
        }

        public ActionResult AutocompleteSchoolsObj(string term, string city, string state)
        {
            if (!string.IsNullOrWhiteSpace(state) && !string.IsNullOrWhiteSpace(city))
            {
                log.Debug("Making a request for city {0} state {1} term {2}", city, state, term);
                var schoolsByTownZip = new SchoolDataProvider(GetUserName()).GetSchoolsByTownZip(city, state);
                var list = schoolsByTownZip.Where(s => s.Name.ToUpper().Contains(term.ToUpper())).Select(s =>new {s.Name, s.Id}).Distinct().ToList();
                return Json(list, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// find classroom by teacher name and school id
        /// </summary>
        /// <param name="schoolId"></param>
        /// <param name="term"></param>
        /// <returns></returns>
        public ActionResult AutocompleteClassRoom(string schoolId, string term)
        {
/*
            if (!string.IsNullOrWhiteSpace(state) && !string.IsNullOrWhiteSpace(city))
            {
                var schoolsByTownZip = new SchoolDataProvider().GetSchoolsByTownZip(city, state);
                var list = schoolsByTownZip.Where(s => s.Name.ToUpper().Contains(term.ToUpper())).Select(s =>new {s.Name, s.Id}).Distinct().ToList();
                return Json(list, JsonRequestBehavior.AllowGet);
            }
*/
            return Json("", JsonRequestBehavior.AllowGet);
        }
    }
}

SchoolDues/BananaPlanerMVC/Views/Invite/Child.cshtml
@using SchoolDuesLib.Models
@model IEnumerable<SchoolDuesLib.Models.Invitation>

@{
    ViewBag.Title = ViewBag.Student.FirstName + "'s Dashboard";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";

}

<h2>@ViewBag.Student.FirstName's Dashboard</h2>
<div class="row">
    <div class='span9'>
            <div class="white-card">
                <h3 class="section-header">Upcoming Events</h3>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <td>Event</td>
                            <td>Date</td>
                            <td>Time</td>
                            <td>Location</td>
@*                            <td>School</td>*@
                            <td>Teacher</td>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach(var invite in @Model.OrderBy(i=>i.Event.StartTime))
                    {
                        var ev = invite.Event;
                        <tr>
                            <td>@Html.ActionLink(ev.Name, "Get", "Invite", new {invite.Id}, null)</td>
                            <td>@ev.StartTime.Value.ToShortDateString()</td>
                            <td>@ev.StartTime.Value.ToShortTimeString()</td>
                            <td>@ev.Location</td>
@*                            <td>@ev.School.Name</td>*@
                            <td>@ev.Teachers</td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
    </div>
</div>

SchoolDues/BananaPlanerMVC/Views/Invite/Get.cshtml
@using BananaPlanerMVC.Models
@using BananaPlanerMVC.Utils
@using SchoolDuesLib.Models
@using SchoolDuesLib.Providers
@model Invitation

@{
    ViewBag.Title = "Event Invitation";
    Layout = "~/Views/Shared/_DashboardLayout.cshtml";
    var children = new ChildDataAccess(User.Identity.Name).GetStudentsByParentUsername(User.Identity.Name);
    var theEvent = Model.Event;
}
@if (!children.Any())
{
    <div class="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong>Warning!</strong> You need to @Html.ActionLink("add children to your profile", "Add", "Student") before you can accept invitations
    </div>
}
<div>
        <div class="row">
            <div class="pull-right">
                <div class="btn-group ">
                    <a class="btn btn-primary" href="#"  onclick="send('@SendMailAction.Organizer', @Model.Id, 'To Event Organizer');">Email Organizer</a>
                </div>
            </div>
        </div>
    <div class="row">
        &nbsp;
    </div>
    <h4>@theEvent.Name</h4>
    <div class="row">
        <div class='span4'>
            <div class="white-card">
                Location: @theEvent.Location<br/>
                @if (theEvent.SchoolId != null)
                {
                    @:Teacher: @theEvent.Teachers
                }
                else
                {
                    @:Organizer: @theEvent.CreatedBy.Format(false)
                }
            </div>
        </div>
        <div class='span4'>
            <div class="white-card">
                Date: @theEvent.StartTime.Value.ToShortDateString()<br/>
                Time: @(theEvent.StartTime.Value.ToShortTimeString() + " - " + theEvent.EndTime.Value.ToShortTimeString())<br/>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8">
            <div class="white-card">
                @foreach( var line in theEvent.Description.Split('\r'))
                {
                    @line <br/>
                }
            </div>
        </div>
    </div>
    <div class="row">
        <div class='span4'>
            <div class="white-card">
                <h4>Participants</h4>
                <table class="table">
                    <thead>
                        <tr>
                            <th >Responded(@theEvent.Invitations.Count(i => i.Status == InvitationStatus.Accepted))</th>
                        </tr>
                    </thead>
                    @foreach (var invite in theEvent.Invitations.Where(i => i.Student != null))
                    {
                        <tr><td>@invite.FormatParticipantName(false)</td></tr>
                    }
                </table>
            </div>
        </div>
        @if (theEvent.NeedSupplies == true)
        {
            <div class='span4'>
                <div class="white-card">
                    <h4>Supplies</h4>
                    <table class="table">
                        <thead><tr><th colspan="2">Items Needed</th></tr></thead>
                        @foreach (var supply in theEvent.Supplies)
                        {
                            <tr>
                                <td>@supply.Description</td>
                                <td>
                                    @if (supply.Accepted != null)
                                    {
                                        <div>@supply.Accepted.Format(false)</div>
                                    }
                                    else
                                    {
                                        @Html.ActionLink("Sign up", "AcceptSupply", "Invite", new { supply.Id }, new {@class="btn"})
                                    }
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        }
        @if (theEvent.NeedVolunteers == true)
        {
            <div class='span4'>
                <div class="white-card">
                    <h4>Volunteers</h4>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Time / Volunteers</th>
                            </tr>
                        </thead>
                        @foreach (var spot in theEvent.VolunteerSpots.OrderBy(s => s.StartTime).ThenBy(s => s.EndTime))
                        {
                            <tr>
                                <td>@string.Format("{0} - {1}", spot.StartTime.ToShortTimeString(), spot.EndTime.ToShortTimeString())<br/>
                                    @foreach (var vol in spot.Accepted)
                                    {
                                        @vol.Format(false)<br/>
                                    }
                                    @if (spot.Accepted.Count() < spot.NumberOfVolunteers)
                                    {
                                        @Html.ActionLink("Sign up", "AcceptVolunteer", "Invite", new { spot.Id }, new {@class="btn"})
                                    }
                                </td></tr>
                        }
                    </table>                                
                </div>
            </div>
        }
    </div>
    <div class="row">
        <div class="span9">
            <div class="pull-right">
                @if (@Model.Status != InvitationStatus.Accepted)
                {
                    if (theEvent.FundsPerPerson == null && theEvent.FundsTotal == null)
                    {
                        <div class="btn-group">
                        <button class="btn dropdown-toggle btn-large btn-danger" data-toggle="dropdown">Accept <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                @foreach (var child in children)
                                {
                                    <li>
                                        @Html.ActionLink("Accept as " + child.FirstName, "Accept", "Invite", new { id = Model.Id, childId = child.Id }, null);
                                    </li>
                                }
                                <li>
                                    @Html.ActionLink("Add Child", "Add", "Student")
                                </li>
                            </ul>
                        </div>
                    }
                    else if (theEvent.FundsPerPerson != null)
                    {
                        <a href="#" id="whyDwolla">Why do we use Dwolla?</a>
                        <div class="btn-group">
                        <button class="btn dropdown-toggle" data-toggle="dropdown">Pay $@theEvent.FundsPerPerson and Accept <span class="caret"></span></button>
                            <ul class="dropdown-menu">
                                @foreach (var child in children)
                                {
                                    <li>
                                        @Html.ActionLink(string.Format("Accept for {0} (${1})", child.FirstName, theEvent.FundsPerPerson), "Accept", "Invite", new { id = Model.Id, childId = child.Id }, null)
                                    </li>
                                }
                                <li>
                                    @Html.ActionLink("Add Child", "Add", "Student")
                                </li>
                            </ul>
                        </div>
@*
                        <a href="#" onclick="testDwolla();">.</a>
*@
                    }
                }
                else
                {
                    if (theEvent.FundsPerPerson == null && theEvent.FundsTotal == null)
                    {
                        @:You accepted this invitation on @Model.AcceptedOn.Value.ToShortDateString()
                    }
                    else if (theEvent.FundsPerPerson != null)
                    {
                        @:You accepted this invitation on @Model.AcceptedOn.Value.ToShortDateString() and paid $@Model.Event.FundsPerPerson
                    }
                }                
            </div>
        </div>
    </div>
</div>
@section ScriptBottom {

    <script type="text/javascript">
        $(document).ready(function() {
            $('#whyDwolla').qtip({
                content: 'Dwolla accepts payments from your bank account rather than credit cards thus saving money for your school by not paying a credit card processing fee.',
                style: {
                    classes: 'myCustomClass' // max-width: 350px;
                },
                show: { event: 'click' }
            });
        });
    </script>
    @{ Html.RenderPartial("_SendEmail"); }

}

SchoolDues/BananaPlanerMVC/Views/Invite/Login.cshtml
@model BananaPlanerMVC.Models.LoginModel

@{
    ViewBag.Title = "Log in";
}

<section class='section-wrapper create-account-page-w'>
    <div class='container'>
        <div class='row'>
            <div class='span4 offset2'>
                <div class='white-card extra-padding'>
                    <section class="social" id="socialLoginForm">
                        <h4>Use one of the services below to login</h4>
                        @Html.Action("ExternalLoginsList", "Account", new { ReturnUrl =  @ViewBag.ReturnUrl})
                        @Html.ActionLink("View and respond as a guest" , "GetGuest", "Invite", new {Id = @ViewBag.Id}, new {@class="btn"})
                    </section>
                </div>
            </div>
            <div class='span4 '>
                <div class='white-card extra-padding'>
                    <h3 align="center">Why Register?</h3>
                    <ul>
                        <li>Track all your invitations</li>
                        <li>Create and track your own events</li>
                        <li>Volunteer to bring supplies and sign-up to help out</li>
                        <li>Add your kids and track all their events automatically on the master calendar</li>
                        <li>Allow invitees to select what time slots they want to volunteer</li>
                        <li>Allow invitees to select what items to bring to an event</li>
                        <li>One place to wrangle your kids' invitations and activities</li>
                    </ul>
                    The best tool for managing volunteers, fundraisers, sign-ups parties, sports games and everything else in your kids' schedule
                    <h2 align="center">And it's FREE!!!</h2>
                </div>
            </div>
        </div>
    </div>
</section>